server:
  port: 8081
spring:
  servlet:
    multipart:
      max-request-size: 1024MB #设置总上传数据总大小
      max-file-size: 500MB #设置单个文件最大长度
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lifediary?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
